name: ai_salesman
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  change_app_package_name: ^1.2.0
  flutter_launcher_icons: ^0.14.4
  rename_app: ^1.6.1


flutter_launcher_icons:
  image_path_ios: "assets/icons/launcher_icon.png"
  image_path_android: "assets/icons/launcher_icon.png"
  adaptive_icon_foreground: "assets/icons/launcher_icon.png"
  ios: true
  android: true
  adaptive_icon_background: "#ffffff"
  remove_alpha_ios: true



flutter:
  uses-material-design: true
  assets:
    - assets/


